spring:
 datasource:
    #    url: jdbc:mysql://localhost:3306/std_upload?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/std_upload?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456m

logging:
  level:
    com.stdwork_management.mapper: debug