spring:
 datasource:
    #    url: jdbc:mysql://localhost:3306/std_upload?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://172.20.20.65:3306/std_upload?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456m


logging:
  level:
    com.stdwork_management.mapper: debug